name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history for better SonarQube analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Set your project's Node.js version

      - name: Install Dependencies
        run: npm ci

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Docker Login
        run: echo "${{ secrets.Dockerhub_token }}" | docker login -u "${{ secrets.Dockerhub_username }}" --password-stdin

      - name: Docker Build and Push
        run: |
          docker build -t swiggy-main .
          docker tag swiggy-main emmabongo/swiggy-main:latest
          docker push emmabongo/swiggy-main:latest
